export enum ActionName {
  UpdateApps = "updateApps",
  UpdateItem = "updateItem",
  RenameItem = "renameItem",
  FilterHistory = "filterHistory",
  FocusSearchInput = "focusSearchInput",
  ToggleFilter = "toggleFilter",
  OpenWith = "openWith",
  FormatText = "formatText",
  PasteWithTransformation = "pasteWithTransformation",
  UpdateTags = "updateTags",
  NewTag = "newTag",
  UpdateTag = "updateTag",
  DeleteTag = "deleteTag",
  SwitchTextType = "switchTextType",
}
