name: Build and Release

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-macos:
    # Use an older macOS runner - macos-12 has macOS Monterey + Xcode 14.x
    # macos-13 has macOS Ventura + Xcode 14.x/15.x
    runs-on: macos-latest
    
    env:
      MOBROWSER_KEY: ${{ vars.MOBROWSER_KEY }}
      CLIPBOOK_TEAM_ID: ${{ vars.CLIPBOOK_TEAM_ID }}
      CLIPBOOK_APPLE_ID: ${{ vars.CLIPBOOK_APPLE_ID }}
      CLIPBOOK_PASSWORD: ${{ vars.CLIPBOOK_PASSWORD }}
      CLIPBOOK_CODESIGN_IDENTITY: ${{ vars.CLIPBOOK_CODESIGN_IDENTITY }}
      BUILD_CERT_BASE64: ${{ secrets.DEVELOPER_ID_APPLICATION_CERT }}
      P12_PASSWORD: ${{ secrets.DEVELOPER_ID_APPLICATION_CERT_PASSWORD }}
      KEYCHAIN_PASSWORD: ${{ secrets.MAC_KEYCHAIN_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm install
      
      - name: Restore licensing files
        run: |
          mkdir -p src-cpp/src/licensing
          echo "${{ secrets.LICENSING_H }}" | base64 -d > src-cpp/src/licensing/licensing.h
          echo "${{ secrets.LICENSING_MM }}" | base64 -d > src-cpp/src/licensing/licensing.mm

      - name: Set up keychain & build ClipBook for arm64
        run: |
          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

          # Decode and create keychain
          echo -n "$BUILD_CERT_BASE64" | base64 --decode -o "$CERTIFICATE_PATH"
          security create-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN_PATH"
          security set-keychain-settings -lut 21600 "$KEYCHAIN_PATH"
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN_PATH"

          # Import Apple root certs (must be done BEFORE importing the certificate)
          curl -O https://www.apple.com/certificateauthority/AppleRootCA-G3.cer
          curl -O https://www.apple.com/certificateauthority/AppleWWDRCAG6.cer
          curl -O https://www.apple.com/certificateauthority/DeveloperIDG2CA.cer
          security import AppleRootCA-G3.cer -k "$KEYCHAIN_PATH" -T /usr/bin/codesign -T /usr/bin/productsign
          security import AppleWWDRCAG6.cer -k "$KEYCHAIN_PATH" -T /usr/bin/codesign -T /usr/bin/productsign
          security import DeveloperIDG2CA.cer -k "$KEYCHAIN_PATH" -T /usr/bin/codesign -T /usr/bin/productsign

          # Import Developer ID certificate with private key
          # Using -T flags to explicitly allow codesign and productsign access
          security import "$CERTIFICATE_PATH" -P "$P12_PASSWORD" -k "$KEYCHAIN_PATH" -T /usr/bin/codesign
          
          # Set partition list to allow access without password prompts
          # This MUST be done immediately after import for it to work properly
          security set-key-partition-list -S apple-tool:,apple: -s -k "$KEYCHAIN_PASSWORD" "$KEYCHAIN_PATH"

          # 🔑 Ensure this keychain is used by all subprocesses
          # Add both our custom keychain AND the login keychain to the search list
          # This ensures system processes can find certificates in both locations
          security list-keychains -d user -s "$KEYCHAIN_PATH" login.keychain
          security default-keychain -s "$KEYCHAIN_PATH"
          
          # Keep the keychain unlocked for the entire build process
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN_PATH"

          # Verify identity exists and is valid
          echo "=== Verifying codesigning identity ==="
          security find-identity -v -p codesigning "$KEYCHAIN_PATH"
          echo "=== All identities in keychain ==="
          security find-identity -v "$KEYCHAIN_PATH"
          
          # Extract the certificate hash (SHA-1) to use instead of the name
          # This is more reliable when specifying --keychain in codesign
          CERT_HASH=$(security find-identity -v -p codesigning "$KEYCHAIN_PATH" | grep "Developer ID Application" | awk '{print $2}')
          echo "Certificate hash: $CERT_HASH"
          
          # Test if codesign can access the identity
          echo "=== Testing codesign access to identity ==="
          # Create a simple test file to sign
          echo "test" > /tmp/test.txt
          
          echo "Test 1: WITH --keychain flag using hash:"
          codesign --keychain "$KEYCHAIN_PATH" -s "$CERT_HASH" /tmp/test.txt && echo "✓ Success with hash" || echo "✗ Failed with hash"
          rm -f /tmp/test.txt
          
          echo "test" > /tmp/test.txt
          echo "Test 2: WITH --keychain flag using name:"
          codesign --keychain "$KEYCHAIN_PATH" -s "$CLIPBOOK_CODESIGN_IDENTITY" /tmp/test.txt && echo "✓ Success with name" || echo "✗ Failed with name"
          rm -f /tmp/test.txt
          
          echo "test" > /tmp/test.txt
          echo "Test 3: WITHOUT --keychain flag using hash (default search path):"
          codesign -s "$CERT_HASH" /tmp/test.txt && echo "✓ Success - will use this approach!" || echo "✗ Failed"
          rm -f /tmp/test.txt
          
          echo "test" > /tmp/test.txt
          echo "Test 4: WITHOUT --keychain flag using name (default search path):"
          codesign -s "$CLIPBOOK_CODESIGN_IDENTITY" /tmp/test.txt && echo "✓ Success - will use this approach!" || echo "✗ Failed"
          rm -f /tmp/test.txt

          # Override CLIPBOOK_CODESIGN_IDENTITY with the certificate hash
          # The tests showed that codesign can find the identity by hash but not by name
          export CLIPBOOK_CODESIGN_IDENTITY=$CERT_HASH
          echo "CLIPBOOK_CODESIGN_IDENTITY=$CLIPBOOK_CODESIGN_IDENTITY (using hash instead of name)"
          
          # DO NOT set CLIPBOOK_CODESIGN_KEYCHAIN - let codesign use the default keychain search path
          # This avoids the "no identity found" error when codesign looks only in the specified keychain
          echo "Note: NOT setting CLIPBOOK_CODESIGN_KEYCHAIN to allow codesign to use default search path"

          # Export the environment variable
          echo "CLIPBOOK_CODESIGN_IDENTITY=$CERT_HASH" >> $GITHUB_ENV

          # Run the build
          npm run mobrowser build -- --arm64 --verbose
      
      # - name: Upload DMG as artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: ClipBook-macOS
      #     path: |
      #       build-dist/pack/*.dmg
      #       dist/*.dmg
      #     retention-days: 30
      
      # - name: Create GitHub Release
      #   uses: softprops/action-gh-release@v1
      #   if: startsWith(github.ref, 'refs/tags/')
      #   with:
      #     files: |
      #       build-dist/pack/*.dmg
      #       dist/*.dmg
      #     draft: false
      #     prerelease: false
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}